#define NO_MATCH_ADDR_OFFSET_BYTECODE		"WARNING: No Bytecode Parameter Match, probably you're not using an appropriate firmware"



#define ADDRESS_CONDITION_PROCEDURE  0x770

//settaggio indirizzi per la sezione che contiene i parametri di stato
//parametri bytecode

#define PARAMETER_ADDR_OFFSET_BYTECODE_1		0x0418
#define PARAMETER_ADDR_BYTECODE_1			0x0830
#define PARAMETER_ADDR_OFFSET_BYTECODE_2		0x0610
#define PARAMETER_ADDR_BYTECODE_2			0x0C20
#define LENGTH_PARAMETER_REGION				0x0028


#define EDCFQCUR 					0x0260




//descrittori di stato
#define COMBINATION_ADDR_BYTECODE_1			PARAMETER_ADDR_BYTECODE_1 + (LENGTH_PARAMETER_REGION * 2)
#define COMBINATION_ADDR_BYTECODE_2			PARAMETER_ADDR_BYTECODE_2 + (LENGTH_PARAMETER_REGION * 2)
#define LENGTH_PARAMETER_AND_COMBINATION_REGION		0x01B8
	
	
//stati
#define STATE_ADDR_BYTECODE_1			( PARAMETER_ADDR_BYTECODE_1 + (LENGTH_PARAMETER_AND_COMBINATION_REGION * 2) )
#define STATE_ADDR_BYTECODE_2			( PARAMETER_ADDR_BYTECODE_2 + (LENGTH_PARAMETER_AND_COMBINATION_REGION * 2) )



#define GPR_CONTROL		55
#define GPR_BYTECODE_ADDRESS 	57
#define GPR_CURRENT_STATE	48

#define	SHM_RX_TIME_WORD3	0x078
#define	SHM_RX_TIME_WORD2	0x07A
#define SHM_RX_TIME_WORD1	0x07C
#define	SHM_RX_TIME_WORD0	0x07E

#define	REG_TIMER_DELAY_2	30
#define	REG_TIMER_DELAY_1	31

#define	TIMER_DELAY_2_TIME_OUT	 0x00C0
#define	TIMER_DELAY_1_TIME_OUT	 0x00C2






#define	PROCEDURE_REGISTER_1	44
#define	PROCEDURE_REGISTER_2	46
	
#define PROCEDURE_MEMORY_1 	0x00C8
#define PROCEDURE_MEMORY_2	0x00CC
#define PROCEDURE_MEMORY_3	0x00D0

#define START_STATE_MACHINE	0x0
#define CHANNEL			"PHYREG"
#define TIME_SLOT_POSITION	0x21

#define BYTECODE_CHANNEL	0x17

#define MIN_CONTENTION_WIN_BC	0x1C
#define MAX_CONTENTION_WIN_BC	0x1D
#define CUR_CONTENTION_WIN_BC	0x1E

#define MIN_CONTENTION_WIN_FW	0x2
#define MAX_CONTENTION_WIN_FW	0x4
#define CUR_CONTENTION_WIN_FW	0x6
#define MIN_CONTENTION_WIN_REG	6
#define MAX_CONTENTION_WIN_REG	7
#define CUR_CONTENTION_WIN_REG	8

#define PARAM_CHANNEL		0x02
#define TX_PACKET_DEST_ADD_1	0x03
#define TX_PACKET_DEST_ADD_2	0x04
#define TX_PACKET_DEST_ADD_3	0x05

#define RX_PACKET_SRC_ADD_1	0x06
#define RX_PACKET_SRC_ADD_2	0x07
#define RX_PACKET_SRC_ADD_3	0x08

#define TSF_GPT0_0_CNTHI	0x09
#define TSF_GPT0_0_CNTLO	0x0A
#define TSF_GPT0_1_CNTHI	0x0B
#define TSF_GPT0_1_CNTLO	0x0C
#define TSF_GPT1_0_CNTHI	0x0D
#define TSF_GPT1_0_CNTLO	0x0E
#define TSF_GPT1_1_CNTHI	0x0F
#define TSF_GPT1_1_CNTLO	0x10

#define PRM_14			0x11

#define CHECK_CHANNEL		0x15

#define TIME_SLOT		0x16
#define PRM_10			0x16

#define INFLATION_MUL_BACKOFF	0x18
#define INFLATION_ADD_BACKOFF 	0x19
#define DEFLATION_DIV_BACKOFF 	0x1A
#define DEFLATION_SUB_BACKOFF	0x1B

#define SET_VALUE		0x1F
#define PRM_12			0x1F

#define CHECK_VALUE		0x20
#define PRM_13			0x20

#define PRM_11			0x21

#define TIME_SLOT_POSITION_0_R	60
#define TIME_SLOT_POSITION_1_R	61
#define TIME_SLOT_POSITION_2_R	62
#define TIME_SLOT_POSITION_3_R	63







