
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.4 EDK_P.49d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xv6_ddrx.h"

/*
* The configuration table for devices
*/

XV6_Ddrx_Config XV6_Ddrx_ConfigTable[] =
{
	{
		XPAR_DDR3_SODIMM_DEVICE_ID,
		XPAR_DDR3_SODIMM_S_AXI_BASEADDR,
		XPAR_DDR3_SODIMM_S_AXI_HIGHADDR,
		XPAR_DDR3_SODIMM_S_AXI_CTRL_BASEADDR,
		XPAR_DDR3_SODIMM_S_AXI_CTRL_HIGHADDR,
		XPAR_DDR3_SODIMM_ECC,
		XPAR_DDR3_SODIMM_ECC_TEST,
		XPAR_DDR3_SODIMM_ECC_ONOFF_REGISTER
	}
};


