COMPILER=
ARCHIVER=
CP=cp
COMPILER_FLAGS=-O2 -c -g
EXTRA_COMPILER_FLAGS = 
LIB=libxil.a
LEVEL=0

INCLUDEDIR=../../../include/
INCLUDES=-I./include/ -I${INCLUDEDIR}

INCLUDEFILES=./include/*h

libs: dummy
include: dummy
	${CP} -rf ${INCLUDEFILES} ${INCLUDEDIR}
dummy:
clean:
