
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 3.08.a
 PARAMETER PROC_INSTANCE = mb_low
 PARAMETER STDIN = mb_low_uart
 PARAMETER STDOUT = mb_low_uart
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 1.14.a
 PARAMETER HW_INSTANCE = mb_low
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = mac_log_bram_ctrl
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = mb_low_dlmb_bram_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = mb_low_ilmb_bram_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 2.04.a
 PARAMETER HW_INSTANCE = mb_low_timer
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 2.00.a
 PARAMETER HW_INSTANCE = mb_low_uart
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = mbox
 PARAMETER DRIVER_VER = 3.02.a
 PARAMETER HW_INSTANCE = mb_mailbox
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = pkt_buff_rx_bram_ctrl
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = pkt_buff_tx_bram_ctrl
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = mutex
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = pkt_buffer_mutex
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = radio_controller_axi
 PARAMETER DRIVER_VER = 3.00.d
 PARAMETER HW_INSTANCE = radio_controller_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = w3_ad_controller_axi
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = w3_ad_controller_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = w3_clock_controller_axi
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = w3_clock_controller_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = w3_iic_eeprom_axi
 PARAMETER DRIVER_VER = 1.00.b
 PARAMETER HW_INSTANCE = w3_iic_eeprom_onboard
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = w3_userio_axi
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = w3_userio
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = wlan_agc_axiw
 PARAMETER DRIVER_VER = 1.00.j
 PARAMETER HW_INSTANCE = wlan_agc
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = wlan_mac_dcf_hw_axiw
 PARAMETER DRIVER_VER = 1.00.v
 PARAMETER HW_INSTANCE = wlan_mac_dcf_hw
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = wlan_phy_rx_pmd_axiw
 PARAMETER DRIVER_VER = 2.03.m
 PARAMETER HW_INSTANCE = wlan_phy_rx
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = wlan_phy_tx_pmd_axiw
 PARAMETER DRIVER_VER = 2.00.m
 PARAMETER HW_INSTANCE = wlan_phy_tx
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = fsm_buffer_ctrl
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = mutex
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = fsm_mutex
END


