
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.4 EDK_P.49d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmbox.h"

/*
 * The configuration table for devices
 */

XMbox_Config XMbox_ConfigTable[] =
{
	{
		 XPAR_MB_MAILBOX_IF_0_DEVICE_ID, 
		 XPAR_MB_MAILBOX_IF_0_BASEADDR, 
		 XPAR_MB_MAILBOX_IF_0_USE_FSL,
		 XPAR_MB_MAILBOX_IF_0_SEND_FSL,
		 XPAR_MB_MAILBOX_IF_0_RECV_FSL
	},
};
