
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.4 EDK_P.49d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmutex.h"

/*
* The configuration table for devices
*/

XMutex_Config XMutex_ConfigTable[] =
{
	{
		 XPAR_FSM_MUTEX_IF_0_DEVICE_ID, 
		 XPAR_FSM_MUTEX_IF_0_BASEADDR, 
		 XPAR_FSM_MUTEX_IF_0_NUM_MUTEX, 
		 XPAR_FSM_MUTEX_IF_0_ENABLE_USER, 
	},
	{
		 XPAR_PKT_BUFFER_MUTEX_IF_0_DEVICE_ID, 
		 XPAR_PKT_BUFFER_MUTEX_IF_0_BASEADDR, 
		 XPAR_PKT_BUFFER_MUTEX_IF_0_NUM_MUTEX, 
		 XPAR_PKT_BUFFER_MUTEX_IF_0_ENABLE_USER, 
	},
};
