/*
 * transition.h
 *
 *  Created on: Oct 10, 2013
 *      Author: Nicolo' Facchi
 */

#ifndef WMP_TRANSITION_H_
#define WMP_TRANSITION_H_

/* Macros, masks and shifts for bytecode interpretation
 *
 * All these macros exepct an u64 as parameters
 */
#define WMP_TRANSITION_RESERVED_MASK				0x0000FFFF00000000
#define WMP_TRANSITION_RESERVED_SHIFT				32
#define WMP_TRANSITION_GET_RESERVED(tran)			\
	((u16)(((tran) & WMP_TRANSITION_RESERVED_MASK) >> WMP_TRANSITION_RESERVED_SHIFT))

#define WMP_TRANSITION_EVENT_CONDITION_MASK			0x0000FF0000000000
#define WMP_TRANSITION_EVENT_CONDITION_SHIFT		40
#define WMP_TRANSITION_GET_EVENT_CONDITION(tran)	\
	((u8)(((tran) & WMP_TRANSITION_EVENT_CONDITION_MASK) >> WMP_TRANSITION_EVENT_CONDITION_SHIFT))

#define WMP_TRANSITION_EV_COND_PARAM_MASK			0x0000000000F00000
#define WMP_TRANSITION_EV_COND_PARAM_SHIFT			20
#define WMP_TRANSITION_GET_EV_COND_PARAM(tran)		\
	((u8)(((tran) & WMP_TRANSITION_EV_COND_PARAM_MASK) >> WMP_TRANSITION_EV_COND_PARAM_SHIFT))

#define WMP_TRANSITION_EV_COND_PARAM_MASK_2			0x00000000F0000000
#define WMP_TRANSITION_EV_COND_PARAM_SHIFT_2		28
#define WMP_TRANSITION_GET_EV_COND_PARAM_2(tran)	\
	((u8)(((tran) & WMP_TRANSITION_EV_COND_PARAM_MASK_2) >> WMP_TRANSITION_EV_COND_PARAM_SHIFT_2))

#define WMP_TRANSITION_ACTION_PARAM_MASK			0x00000000000F0000
#define WMP_TRANSITION_ACTION_PARAM_SHIFT			16
#define WMP_TRANSITION_GET_ACTION_PARAM(tran)		\
	((u8)(((tran) & WMP_TRANSITION_ACTION_PARAM_MASK) >> WMP_TRANSITION_ACTION_PARAM_SHIFT))

#define WMP_TRANSITION_ACTION_PARAM_MASK_2			0x00000000F000000
#define WMP_TRANSITION_ACTION_PARAM_SHIFT_2			24
#define WMP_TRANSITION_GET_ACTION_PARAM_2(tran)		\
	((u8)(((tran) & WMP_TRANSITION_ACTION_PARAM_MASK_2) >> WMP_TRANSITION_ACTION_PARAM_SHIFT_2))

#define WMP_TRANSITION_ACTION_MASK					0x000000000000FF00
#define WMP_TRANSITION_ACTION_SHIFT					8
#define WMP_TRANSITION_GET_ACTION(tran)				\
	((u8)(((tran) & WMP_TRANSITION_ACTION_MASK) >> WMP_TRANSITION_ACTION_SHIFT))

#define WMP_TRANSITION_NEXT_STATE_MASK				0x00000000000000FF
#define WMP_TRANSITION_NEXT_STATE_SHIFT				0
#define WMP_TRANSITION_GET_NEXT_STATE(tran)			\
	((u16)(((tran) & WMP_TRANSITION_NEXT_STATE_MASK) >> WMP_TRANSITION_NEXT_STATE_SHIFT))


#endif /* TRANSITION_H_ */
