#!/bin/bash

#export PYTHONPATH=$PYTHONPATH:/opt/local/lib/python2.6/site-packages

if [ $# -lt 1 ]; then
	echo $0 CHANNEL
	exit 1
fi

CHANNEL=$1
GAIN=28
#MILLISECONDS=30000
MILLISECONDS=5000
DECIM=8
FREQ=$((2412+5*(${CHANNEL}-1)))
RATE=25
#usrp_rx_cfile.py -d ${DECIM} -f ${FREQ}M -g $GAIN -s -N $((100000/${DECIM}*${MILLISECONDS})) f${FREQ}_d${DECIM}_g${GAIN}.raw
uhd_rx_cfile --samp-rate ${RATE}M -f ${FREQ}M -g $GAIN -s -N $(($RATE*1000*${MILLISECONDS})) f${FREQ}_d${DECIM}_g${GAIN}.raw

