
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.4 EDK_P.49d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: WARP/XilNet MAC Configuration File
*
*******************************************************************/


/***************************** Include Files *********************************/

#include <string.h>
#include <xilnet_config.h>


/************************* Ethernet 0 Definitions ****************************/


// Variables for ETH 0
//   NONE - WARPxilnet library configured to ignore ETH 0

// Buffers for ETH 0
//   NONE - WARPxilnet library configured to ignore ETH 0


/************************* Ethernet 1 Definitions ****************************/


// Variables for ETH 1
XLlFifo              ETH_1_FIFO_Instance;

// Buffers for ETH 1
unsigned int recvBuffer_eth_1[XILNET_ETH_1_NUM_RECV_BUF*((XILNET_ETH_1_BUF_SIZE+3)/4)];
unsigned int sendBuffer_eth_1[(XILNET_ETH_1_BUF_SIZE+3)/4];
struct xilsock_socket xilsock_sockets_eth_1[NO_OF_XILSOCKS];
struct xilnet_udp_conn xilnet_udp_conns_eth_1[XILNET_MAX_UDP_CONNS];


/*************************** Ethernet Variables ******************************/


// Ethernet Device Structure
xilnet_eth_device eth_device[XILNET_NUM_ETH_DEVICES];


void xilnet_init_eth_device_struct(unsigned int eth_dev_num) {

    switch( eth_dev_num ) {
        case XILNET_ETH_0:
            eth_device[eth_dev_num].uses_driver          = 0;
            eth_device[eth_dev_num].inf_type             = XILNET_AXI_DMA_INF;
            eth_device[eth_dev_num].inf_id               = XILNET_ETH_0_INF_DEVICE_ID;
            eth_device[eth_dev_num].inf_ref              = 0;
            eth_device[eth_dev_num].inf_cfg_ref          = 0;
            eth_device[eth_dev_num].inf_dma_id           = 0;
            eth_device[eth_dev_num].inf_dma_ref          = 0;
            eth_device[eth_dev_num].inf_dma_cfg_ref      = 0;
            eth_device[eth_dev_num].dma_rx_ring_ref      = 0;
            eth_device[eth_dev_num].dma_tx_ring_ref      = 0;
            eth_device[eth_dev_num].dma_rx_bd_ref        = 0;
            eth_device[eth_dev_num].dma_tx_bd_ref        = 0;
            eth_device[eth_dev_num].dma_rx_bd_cnt        = XILNET_ETH_0_RXBD_CNT;
            eth_device[eth_dev_num].dma_tx_bd_cnt        = XILNET_ETH_0_TXBD_CNT;
            eth_device[eth_dev_num].xilsock_status_flag  = 0;
            eth_device[eth_dev_num].sync_IP_octet        = 255;
            eth_device[eth_dev_num].is_xilsock_init      = 0;
            eth_device[eth_dev_num].xilsock_sockets      = 0;
            eth_device[eth_dev_num].is_udp_init          = 0;
            eth_device[eth_dev_num].xilnet_udp_conns     = 0;
            eth_device[eth_dev_num].buf_size             = XILNET_ETH_0_BUF_SIZE;
            eth_device[eth_dev_num].num_recvbuf          = XILNET_ETH_0_NUM_RECV_BUF;
            eth_device[eth_dev_num].recvbuf              = 0;
            eth_device[eth_dev_num].sendbuf              = 0;
            break;
        case XILNET_ETH_1:
            eth_device[eth_dev_num].uses_driver          = 1;
            eth_device[eth_dev_num].inf_type             = XILNET_AXI_FIFO_INF;
            eth_device[eth_dev_num].inf_id               = XILNET_ETH_1_INF_DEVICE_ID;
            eth_device[eth_dev_num].inf_ref              = &ETH_1_FIFO_Instance;
            eth_device[eth_dev_num].inf_cfg_ref          = 0;
            eth_device[eth_dev_num].inf_dma_id           = 0;
            eth_device[eth_dev_num].inf_dma_ref          = 0;
            eth_device[eth_dev_num].inf_dma_cfg_ref      = 0;
            eth_device[eth_dev_num].dma_rx_ring_ref      = 0;
            eth_device[eth_dev_num].dma_tx_ring_ref      = 0;
            eth_device[eth_dev_num].dma_rx_bd_ref        = 0;
            eth_device[eth_dev_num].dma_tx_bd_ref        = 0;
            eth_device[eth_dev_num].dma_rx_bd_cnt        = 0;
            eth_device[eth_dev_num].dma_tx_bd_cnt        = 0;
            eth_device[eth_dev_num].xilsock_status_flag  = 0;
            eth_device[eth_dev_num].sync_IP_octet        = 255;
            eth_device[eth_dev_num].is_xilsock_init      = 0;
            eth_device[eth_dev_num].xilsock_sockets      = &xilsock_sockets_eth_1;
            eth_device[eth_dev_num].is_udp_init          = 0;
            eth_device[eth_dev_num].xilnet_udp_conns     = &xilnet_udp_conns_eth_1;
            eth_device[eth_dev_num].buf_size             = XILNET_ETH_1_BUF_SIZE;
            eth_device[eth_dev_num].num_recvbuf          = XILNET_ETH_1_NUM_RECV_BUF;
            eth_device[eth_dev_num].recvbuf              = (unsigned int *)&recvBuffer_eth_1;
            eth_device[eth_dev_num].sendbuf              = (unsigned int *)&sendBuffer_eth_1;
            break;
        default:
    		xil_printf("  **** ERROR:  Trying to initialize Ethernet device %d.  Only %d configured in the HW.", (eth_dev_num+1), XILNET_NUM_ETH_DEVICES);
	    break;
    }
}


/*****************************************************************************/

